### PR TITLE
Add/57 - Design Updates to Recipes Cards

### PR DESCRIPTION
**Pull request by viscosho**
This is for doing this improvements: https://github.com/lightspeeddevelopment/lsx-health-plan/issues/54

### CODE REVIEW

**Review by krugazul — CHANGES_REQUESTED** [review]
@viscosho  there are a few things that still need to happen please.

- [x] Make sure "Serves" is [first](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/templates/table-recipe-data.php#L38) 
Screenshot 2020-01-28 at 09 34 56

- [x] Add `__( 'People', 'lsx-health-plan' )` , so it always [outputs](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/templates/table-recipe-data.php#L44). 
This will need to be dynamic, you will need to check to see if the `$serves` value is 1, and change the label to "Person".  Something like.
```
if ( 1 === (int) $serves ) {
	$serves_label = __( 'Person', 'lsx-health-plan' );
} else {
	$serves_label = __( 'People', 'lsx-health-plan' );
}
```

- [x] We are going to restrict the [custom field](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/classes/class-recipe.php#L289) to only allow number inputs.   You can see how to do that [here](https://github.com/CMB2/CMB2/wiki/Tips-&-Tricks#limit-text-field-to-numbers-only)

**Comment by viscosho** [comment]
@krugazul  I added those fixes in the latest push:

- "Serves" will always be first
- Serves will always output (even is if empty, showing 1)
- Serves field is restricted to numbers

Please review

**Review by krugazul — APPROVED** [review]
@viscosho I have tested the changes on the [LSX HP demo site,](https://lsx-health-plan.lsdev.biz/recipes/) they are working perfectly, thanks.

**Comment by krugazul** [comment]
**Description of the Change**
The meta displaying below the recipe cards on the archive pages were updated, the information that displays and the styling.

**Benefits**
The meta information fits the box better, and looks good.

**Checklist**
 - [x] The code follows the code style of this project.
 - [x] All new and existing tests passed.

**Issues**
#56

**Pull request merged**
